apiVersion: v1
kind: Secret
metadata:
  name: dify-credentials
  namespace: dify
data:
  # Base64 encoded postgres username, default is postgres
  pg-username: cG9zdGdyZXM=
  # Base64 encoded postgres password, default is difyai123456
  pg-password: ZGlmeWFpMTIzNDU2
  # Base64 encoded postgres host, default is dify-postgres
  pg-host: ZGlmeS1wb3N0Z3Jlcw==
  # Base64 encoded postgres port 5432
  pg-port: NTQzMg==
  # Base64 encoded redis username, default is empty
  redis-username: ''
  # Base64 encoded redis password, default is difyai123456
  redis-password: ZGlmeWFpMTIzNDU2
  # Base64 encoded redis host, default is dify-redis
  redis-host: ZGlmeS1yZWRpcw==
  # Base64 encoded redis port 6379
  redis-port: NjM3OQ==
  # Base64 encoded weaviate host, default is dify-weaviate
  weaviate-host: ZGlmeS13ZWF2aWF0ZQ==
  # Base64 encoded weaviate port 8080
  weaviate-port: ODA4MA==
type: Opaque
