# Namespace for Dify
apiVersion: v1
kind: Namespace
metadata:
  name: dify

---
# Namespace for Helm Operator
apiVersion: v1
kind: Namespace
metadata:
  name: helm-operator

---
# Helm Operator CRDs
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmreleases.helm.cattle.io
spec:
  group: helm.cattle.io
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    singular: helmrelease
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                releaseName:
                  type: string
                chart:
                  type: object
                  properties:
                    name:
                      type: string
                    repository:
                      type: string
                    version:
                      type: string
                values:
                  type: object
                namespace:
                  type: string

---
# Deploy Helm Operator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-operator
  namespace: helm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-operator
  template:
    metadata:
      labels:
        app: helm-operator
    spec:
      containers:
        - name: helm-operator
          image: quay.io/roboll/helm-operator:v1.0.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/helm-operator

---
# HelmRelease for Dify Application
apiVersion: helm.cattle.io/v1
kind: HelmRelease
metadata:
  name: dify
  namespace: dify
spec:
  releaseName: dify
  chart:
    name: dify
    repository: https://borispolonsky.github.io/dify-helm
    version: latest  # Or specify a specific version here
  values:
    image:
      tag: "latest" # Specify your image version if needed
    service:
      type: LoadBalancer

---
# GitRepository Resource for Config Sync (points to your GitHub repository)
apiVersion: apps.open-cluster-management.io/v1
kind: GitRepository
metadata:
  name: dify-config
  namespace: config-management-system
spec:
  repo: "https://github.com/your-user/your-repo"
  branch: main
  interval: 10m0s
  secretRef:
    name: github-token

---
# Kustomization Resource for Config Sync
apiVersion: apps.open-cluster-management.io/v1
kind: Kustomization
metadata:
  name: dify-kustomization
  namespace: config-management-system
spec:
  resources:
    - ./config-sync-namespace.yaml
    - ./helm-operator-crds-and-deployment.yaml
    - ./helm/helm.cattle.io_v1_helmrelease_dify.yaml
