# Namespace for Helm Operator and Dify
apiVersion: v1
kind: Namespace
metadata:
  name: dify

---
# Namespace for Helm Operator
apiVersion: v1
kind: Namespace
metadata:
  name: helm-operator

---
# Helm Operator CRDs
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmreleases.helm.cattle.io
spec:
  group: helm.cattle.io
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    singular: helmrelease
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                releaseName:
                  type: string
                chart:
                  type: object
                  properties:
                    name:
                      type: string
                    repository:
                      type: string
                    version:
                      type: string
                values:
                  type: object
                namespace:
                  type: string

---
# Deploy Helm Operator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-operator
  namespace: helm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-operator
  template:
    metadata:
      labels:
        app: helm-operator
    spec:
      containers:
        - name: helm-operator
          image: bitnami/helm:3.10.3
          imagePullPolicy: IfNotPresent
          command:
            - /bin/helm-operator

---
# HelmRelease for Dify Application
apiVersion: helm.cattle.io/v1
kind: HelmRelease
metadata:
  name: dify
  namespace: dify
spec:
  releaseName: dify
  chart:
    name: dify
    repository: https://borispolonsky.github.io/dify-helm
    version: latest  # You can specify a version or use 'latest'
  values:
    image:
      tag: "latest"  # Specify your image version if needed
    service:
      type: LoadBalancer

---
# Install Helm via a Job (to add repo and update)
apiVersion: batch/v1
kind: Job
metadata:
  name: helm-install-dify
  namespace: dify
spec:
  template:
    spec:
      containers:
      - name: helm
        image: alpine/helm:3.10.3
        command:
          - /bin/sh
          - -c
          - |
            helm repo add dify https://borispolonsky.github.io/dify-helm
            helm repo update
            helm install my-release dify/dify --namespace dify
      restartPolicy: Never
  backoffLimit: 4
